#!/usr/bin/env bash
set -euo pipefail

LAUNCH_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${LAUNCH_DIR}/.." && pwd)"
CARLA_DIR="${REPO_ROOT}/CARLA"
BRIDGE_DIR="${CARLA_DIR}/UB-API/carla-autoware-sumo-bridge"

source "${LAUNCH_DIR}/lib/common.sh"
source "${LAUNCH_DIR}/lib/x11.sh"
source "${LAUNCH_DIR}/lib/preflight.sh"
source "${LAUNCH_DIR}/lib/compose.sh"
source "${LAUNCH_DIR}/carla/stack.sh"
source "${LAUNCH_DIR}/carla/camera_follow.sh"
source "${LAUNCH_DIR}/carla/time_master.sh"
source "${LAUNCH_DIR}/sumo/bridge.sh"
source "${LAUNCH_DIR}/autoware/dds.sh"
source "${LAUNCH_DIR}/autoware/container.sh"
source "${LAUNCH_DIR}/autoware/launch.sh"

BUILD_FOLDER="${BUILD_FOLDER:-v1.0.0}"
CARLA_MAP="${CARLA_MAP:-UBAutonomousProvingGrounds}"
CARLA_MAP_PATH="${CARLA_MAP_PATH:-/Game/Carla/Maps/${CARLA_MAP}}"
CARLA_ARGS="${CARLA_ARGS:--prefernvidia -quality-level=Epic -nosound}"
CARLA_X11_WARN_MESSAGE="xhost did not grant local root X11 access. CARLA or SUMO GUI may fail to render."

DEFAULT_AUTOWARE_HOST_MAP_DIR="${REPO_ROOT}/Autoware/host_data/maps/ub_autonomous_proving_grounds"
DEFAULT_AUTOWARE_MAP_PATH="/host_data/maps/ub_autonomous_proving_grounds"
LEGACY_AUTOWARE_HOST_MAP_DIR="${REPO_ROOT}/Autoware/host_data/ub_autonomous_proving_grounds"
LEGACY_AUTOWARE_MAP_PATH="/host_data/ub_autonomous_proving_grounds"

if [[ -z "${AUTOWARE_HOST_MAP_DIR:-}" && -z "${AUTOWARE_MAP_PATH:-}" ]] && has_files "${LEGACY_AUTOWARE_HOST_MAP_DIR}" && ! has_files "${DEFAULT_AUTOWARE_HOST_MAP_DIR}"; then
  AUTOWARE_HOST_MAP_DIR="${LEGACY_AUTOWARE_HOST_MAP_DIR}"
  AUTOWARE_MAP_PATH="${LEGACY_AUTOWARE_MAP_PATH}"
fi

AUTOWARE_DOCKER_DIR="${AUTOWARE_DOCKER_DIR:-${REPO_ROOT}/Autoware/ub-lincoln-docker/docker}"
AUTOWARE_HOST_MAP_DIR="${AUTOWARE_HOST_MAP_DIR:-${DEFAULT_AUTOWARE_HOST_MAP_DIR}}"
AUTOWARE_MAP_PATH="${AUTOWARE_MAP_PATH:-${DEFAULT_AUTOWARE_MAP_PATH}}"
AUTOWARE_SERVICE="${AUTOWARE_SERVICE:-autoware}"
AUTOWARE_CARLA_HOST="${AUTOWARE_CARLA_HOST:-127.0.0.1}"
AUTOWARE_CARLA_PORT="${AUTOWARE_CARLA_PORT:-2000}"
AUTOWARE_VEHICLE_MODEL="${AUTOWARE_VEHICLE_MODEL:-sample_vehicle}"
AUTOWARE_SENSOR_MODEL="${AUTOWARE_SENSOR_MODEL:-awsim_sensor_kit}"
AUTOWARE_RVIZ="${AUTOWARE_RVIZ:-}"
AUTOWARE_PLANNING_MODULE_PRESET="${AUTOWARE_PLANNING_MODULE_PRESET:-}"
AUTOWARE_E2E_SIMULATOR_TYPE="${AUTOWARE_E2E_SIMULATOR_TYPE:-awsim}"
AUTOWARE_CARLA_POINTCLOUD_RELAY="${AUTOWARE_CARLA_POINTCLOUD_RELAY:-1}"
UB_AUTOWARE_CARLA_IMU_RELAY="${UB_AUTOWARE_CARLA_IMU_RELAY:-1}"
UB_AUTOWARE_CARLA_PLANNING_PRESET="${UB_AUTOWARE_CARLA_PLANNING_PRESET:-1}"
UB_AUTOWARE_EGO_ONLY_PERCEPTION="${UB_AUTOWARE_EGO_ONLY_PERCEPTION:-0}"
UB_AUTOWARE_CARLA_EGO_ROLE_NAME="${UB_AUTOWARE_CARLA_EGO_ROLE_NAME:-ego_vehicle}"
UB_AUTOWARE_CARLA_VEHICLE_TYPE="${UB_AUTOWARE_CARLA_VEHICLE_TYPE:-vehicle.lincoln.mkz_2017}"
UB_AUTOWARE_CARLA_VEHICLE_COLOR="${UB_AUTOWARE_CARLA_VEHICLE_COLOR:-}"
# Default captured from RViz 2D Pose Estimate and converted from ROS map to CARLA coordinates.
UB_AUTOWARE_CARLA_SPAWN_POINT="${UB_AUTOWARE_CARLA_SPAWN_POINT:--214.130,3.295,0.030,0,0,0.722}"
UB_AUTOWARE_CARLA_PROJECT_SPAWN_TO_ROAD="${UB_AUTOWARE_CARLA_PROJECT_SPAWN_TO_ROAD:-False}"
UB_AUTOWARE_CARLA_PACKAGE_SHARE="${UB_AUTOWARE_CARLA_PACKAGE_SHARE:-/autoware/install/autoware_carla_interface/share/autoware_carla_interface}"
UB_AUTOWARE_CARLA_OBJECTS_DEFINITION_FILE="${UB_AUTOWARE_CARLA_OBJECTS_DEFINITION_FILE:-${UB_AUTOWARE_CARLA_PACKAGE_SHARE}/objects_ub_lincoln.json}"
UB_AUTOWARE_CARLA_RAW_VEHICLE_CMD_CONVERTER_CONFIG="${UB_AUTOWARE_CARLA_RAW_VEHICLE_CMD_CONVERTER_CONFIG:-${UB_AUTOWARE_CARLA_PACKAGE_SHARE}/raw_vehicle_cmd_converter.ub_lincoln.param.yaml}"
UB_AUTOWARE_CARLA_ALIGN_BASE_LINK_TO_REAR_AXLE="${UB_AUTOWARE_CARLA_ALIGN_BASE_LINK_TO_REAR_AXLE:-1}"
case "${UB_AUTOWARE_CARLA_ALIGN_BASE_LINK_TO_REAR_AXLE,,}" in
  1|true|yes|on) UB_AUTOWARE_CARLA_ALIGN_BASE_LINK_TO_REAR_AXLE="true" ;;
  0|false|no|off) UB_AUTOWARE_CARLA_ALIGN_BASE_LINK_TO_REAR_AXLE="false" ;;
esac
UB_AUTOWARE_CARLA_PUBLISH_SIMULATOR_TF="${UB_AUTOWARE_CARLA_PUBLISH_SIMULATOR_TF:-1}"
case "${UB_AUTOWARE_CARLA_PUBLISH_SIMULATOR_TF,,}" in
  1|true|yes|on) UB_AUTOWARE_CARLA_PUBLISH_SIMULATOR_TF="true" ;;
  0|false|no|off) UB_AUTOWARE_CARLA_PUBLISH_SIMULATOR_TF="false" ;;
esac
UB_AUTOWARE_LIDAR_DETECTION_MODEL="${UB_AUTOWARE_LIDAR_DETECTION_MODEL:-centerpoint/centerpoint}"
UB_AUTOWARE_CARLA_FILTER_EGO_LIDAR_POINTS="${UB_AUTOWARE_CARLA_FILTER_EGO_LIDAR_POINTS:-1}"
case "${UB_AUTOWARE_CARLA_FILTER_EGO_LIDAR_POINTS,,}" in
  1|true|yes|on) UB_AUTOWARE_CARLA_FILTER_EGO_LIDAR_POINTS="true" ;;
  0|false|no|off) UB_AUTOWARE_CARLA_FILTER_EGO_LIDAR_POINTS="false" ;;
esac
UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_X_MIN="${UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_X_MIN:--1.30}"
UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_X_MAX="${UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_X_MAX:-4.35}"
UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_Y_MIN="${UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_Y_MIN:--1.35}"
UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_Y_MAX="${UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_Y_MAX:-1.35}"
UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_Z_MIN="${UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_Z_MIN:--0.50}"
UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_Z_MAX="${UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_Z_MAX:-1.65}"
UB_AUTOWARE_CARLA_EXTERNAL_TICK_TIMEOUT="${UB_AUTOWARE_CARLA_EXTERNAL_TICK_TIMEOUT:-20.0}"
UB_AUTOWARE_INSTALL_PY_DEPS="${UB_AUTOWARE_INSTALL_PY_DEPS:-1}"
UB_AUTOWARE_CARLA_DISABLE_STEER_CONVERGENCE_HOLD="${UB_AUTOWARE_CARLA_DISABLE_STEER_CONVERGENCE_HOLD:-1}"
UB_AUTOWARE_OPERATION_MODE_SHIM="${UB_AUTOWARE_OPERATION_MODE_SHIM:-1}"
UB_AUTOWARE_CARLA_TUNE_SPEED="${UB_AUTOWARE_CARLA_TUNE_SPEED:-1}"
UB_AUTOWARE_CARLA_MAX_VEL="${UB_AUTOWARE_CARLA_MAX_VEL:-11.12}"
UB_AUTOWARE_CARLA_MAX_ACCEL="${UB_AUTOWARE_CARLA_MAX_ACCEL:-1.5}"
UB_AUTOWARE_CARLA_ENGAGE_VELOCITY="${UB_AUTOWARE_CARLA_ENGAGE_VELOCITY:-1.0}"
UB_AUTOWARE_CARLA_TURN_LATERAL_ACCEL_LIMITS="${UB_AUTOWARE_CARLA_TURN_LATERAL_ACCEL_LIMITS:-2.2,2.5,2.8}"
UB_AUTOWARE_CARLA_MIN_TURN_VEL="${UB_AUTOWARE_CARLA_MIN_TURN_VEL:-3.33}"
UB_AUTOWARE_CARLA_INTERSECTION_TURN_VEL="${UB_AUTOWARE_CARLA_INTERSECTION_TURN_VEL:-4.17}"
UB_AUTOWARE_CARLA_THROTTLE_GAIN="${UB_AUTOWARE_CARLA_THROTTLE_GAIN:-2.6}"
UB_AUTOWARE_CARLA_MAX_THROTTLE="${UB_AUTOWARE_CARLA_MAX_THROTTLE:-0.55}"
UB_AUTOWARE_CARLA_MAX_BRAKE="${UB_AUTOWARE_CARLA_MAX_BRAKE:-0.45}"
UB_AUTOWARE_CARLA_BRAKE_DEADBAND="${UB_AUTOWARE_CARLA_BRAKE_DEADBAND:-0.30}"
UB_AUTOWARE_CARLA_THROTTLE_TAU="${UB_AUTOWARE_CARLA_THROTTLE_TAU:-0.45}"
UB_AUTOWARE_CARLA_BRAKE_TAU="${UB_AUTOWARE_CARLA_BRAKE_TAU:-0.25}"
UB_AUTOWARE_CARLA_SOFT_SPEED_LIMIT="${UB_AUTOWARE_CARLA_SOFT_SPEED_LIMIT:-${UB_AUTOWARE_CARLA_MAX_VEL}}"
UB_AUTOWARE_CARLA_SPEED_TAPER_START="${UB_AUTOWARE_CARLA_SPEED_TAPER_START:-8.0}"
UB_AUTOWARE_CARLA_LONGITUDINAL_CONTROL_MODE="${UB_AUTOWARE_CARLA_LONGITUDINAL_CONTROL_MODE:-native}"
UB_AUTOWARE_CARLA_NATIVE_THROTTLE_KP="${UB_AUTOWARE_CARLA_NATIVE_THROTTLE_KP:-0.18}"
UB_AUTOWARE_CARLA_NATIVE_ACCEL_GAIN="${UB_AUTOWARE_CARLA_NATIVE_ACCEL_GAIN:-0.35}"
UB_AUTOWARE_CARLA_NATIVE_BRAKE_GAIN="${UB_AUTOWARE_CARLA_NATIVE_BRAKE_GAIN:-0.15}"
UB_AUTOWARE_CARLA_NATIVE_BRAKE_ACCEL_DEADBAND="${UB_AUTOWARE_CARLA_NATIVE_BRAKE_ACCEL_DEADBAND:-1.2}"
UB_AUTOWARE_CARLA_NATIVE_BRAKE_SPEED_ERROR_DEADBAND="${UB_AUTOWARE_CARLA_NATIVE_BRAKE_SPEED_ERROR_DEADBAND:-2.0}"
UB_AUTOWARE_CARLA_STOP_STEER_RECENTER="${UB_AUTOWARE_CARLA_STOP_STEER_RECENTER:-1}"
case "${UB_AUTOWARE_CARLA_STOP_STEER_RECENTER,,}" in
  1|true|yes|on) UB_AUTOWARE_CARLA_STOP_STEER_RECENTER="true" ;;
  0|false|no|off) UB_AUTOWARE_CARLA_STOP_STEER_RECENTER="false" ;;
esac
UB_AUTOWARE_CARLA_STOP_STEER_SPEED_THRESHOLD="${UB_AUTOWARE_CARLA_STOP_STEER_SPEED_THRESHOLD:-0.20}"
UB_AUTOWARE_CARLA_STOP_STEER_DESIRED_SPEED_THRESHOLD="${UB_AUTOWARE_CARLA_STOP_STEER_DESIRED_SPEED_THRESHOLD:-0.05}"
UB_AUTOWARE_CARLA_STOP_STEER_BRAKE_THRESHOLD="${UB_AUTOWARE_CARLA_STOP_STEER_BRAKE_THRESHOLD:-0.05}"
UB_AUTOWARE_CARLA_PUBLISH_DETECTED_OBJECTS="${UB_AUTOWARE_CARLA_PUBLISH_DETECTED_OBJECTS:-1}"
case "${UB_AUTOWARE_CARLA_PUBLISH_DETECTED_OBJECTS,,}" in
  1|true|yes|on) UB_AUTOWARE_CARLA_PUBLISH_DETECTED_OBJECTS="true" ;;
  0|false|no|off) UB_AUTOWARE_CARLA_PUBLISH_DETECTED_OBJECTS="false" ;;
esac
UB_AUTOWARE_CARLA_DETECTED_OBJECTS_TOPIC="${UB_AUTOWARE_CARLA_DETECTED_OBJECTS_TOPIC:-/carla/ground_truth/perception/object_recognition/detection/objects}"
UB_AUTOWARE_CARLA_DETECTED_OBJECTS_FRAME_ID="${UB_AUTOWARE_CARLA_DETECTED_OBJECTS_FRAME_ID:-map}"
UB_AUTOWARE_CARLA_DETECTED_OBJECTS_MAX_DISTANCE="${UB_AUTOWARE_CARLA_DETECTED_OBJECTS_MAX_DISTANCE:-200.0}"
UB_AUTOWARE_CARLA_DETECTED_OBJECTS_ROLE_NAME="${UB_AUTOWARE_CARLA_DETECTED_OBJECTS_ROLE_NAME:-}"
UB_AUTOWARE_HOST_CONFIG_DDS="${UB_AUTOWARE_HOST_CONFIG_DDS:-1}"
UB_AUTOWARE_RMW_IMPLEMENTATION="${UB_AUTOWARE_RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}"
UB_AUTOWARE_CYCLONEDDS_URI="${UB_AUTOWARE_CYCLONEDDS_URI:-file:///resources/cyclonedds.xml}"
UB_AUTOWARE_CLEAN_STALE_PROCESSES="${UB_AUTOWARE_CLEAN_STALE_PROCESSES:-1}"
UB_KEEP_CARLA="${UB_KEEP_CARLA:-0}"
UB_KEEP_AUTOWARE_ROS="${UB_KEEP_AUTOWARE_ROS:-0}"
UB_KEEP_SUMO="${UB_KEEP_SUMO:-0}"
UB_TRAFFIC_ORCHESTRATOR="${UB_TRAFFIC_ORCHESTRATOR:-sumo}"
UB_KEEP_TIME_MASTER="${UB_KEEP_TIME_MASTER:-0}"
UB_AUTOWARE_CAMERA_FOLLOW="${UB_AUTOWARE_CAMERA_FOLLOW:-1}"
UB_AUTOWARE_CAMERA_FOLLOW_HOST="${UB_AUTOWARE_CAMERA_FOLLOW_HOST:-${AUTOWARE_CARLA_HOST}}"
UB_AUTOWARE_CAMERA_FOLLOW_PORT="${UB_AUTOWARE_CAMERA_FOLLOW_PORT:-${AUTOWARE_CARLA_PORT}}"
UB_AUTOWARE_CAMERA_FOLLOW_ROLE_NAMES="${UB_AUTOWARE_CAMERA_FOLLOW_ROLE_NAMES:-${UB_AUTOWARE_CARLA_EGO_ROLE_NAME}}"
UB_AUTOWARE_CAMERA_FOLLOW_DISTANCE_M="${UB_AUTOWARE_CAMERA_FOLLOW_DISTANCE_M:-8.0}"
UB_AUTOWARE_CAMERA_FOLLOW_HEIGHT_M="${UB_AUTOWARE_CAMERA_FOLLOW_HEIGHT_M:-3.0}"
UB_AUTOWARE_CAMERA_FOLLOW_PITCH_DEG="${UB_AUTOWARE_CAMERA_FOLLOW_PITCH_DEG:--12.0}"
UB_AUTOWARE_CAMERA_FOLLOW_UPDATE_HZ="${UB_AUTOWARE_CAMERA_FOLLOW_UPDATE_HZ:-30.0}"

UB_SUMO_CONFIG="${UB_SUMO_CONFIG:-UBAutonomousProvingGrounds.sumocfg}"
UB_SUMO_STEP_LENGTH="${UB_SUMO_STEP_LENGTH:-0.05}"
UB_SUMO_GUI="${UB_SUMO_GUI:-1}"
UB_SUMO_AUTO_START="${UB_SUMO_AUTO_START:-1}"
UB_SUMO_TLS_MANAGER="${UB_SUMO_TLS_MANAGER:-sumo}"
UB_SUMO_SYNC_VEHICLE_COLOR="${UB_SUMO_SYNC_VEHICLE_COLOR:-0}"
UB_SUMO_SYNC_VEHICLE_LIGHTS="${UB_SUMO_SYNC_VEHICLE_LIGHTS:-0}"
UB_SUMO_EXTRA_ARGS="${UB_SUMO_EXTRA_ARGS:-}"
UB_SUMO_EMPTY_TRAFFIC="${UB_SUMO_EMPTY_TRAFFIC:-0}"

CARLA_STARTED=0
SUMO_STARTED=0
TIME_MASTER_STARTED=0
AUTOWARE_LAUNCH_STARTED=0
CAMERA_FOLLOW_STARTED=0

usage() {
  cat <<EOF
Usage: $(basename "$0") [--dry-run] [--help]

Start single-machine UB-CARLA + Autoware using the custom
autoware_carla_interface in passive mode. With UB_TRAFFIC_ORCHESTRATOR=sumo,
SUMO is the time master. With UB_TRAFFIC_ORCHESTRATOR=none, a CARLA-only
time-master service ticks CARLA.

Defaults:
  BUILD_FOLDER=${BUILD_FOLDER}
  CARLA_MAP=${CARLA_MAP}
  CARLA_ARGS=${CARLA_ARGS}
  UB_TRAFFIC_ORCHESTRATOR=${UB_TRAFFIC_ORCHESTRATOR}
  UB_SUMO_CONFIG=${UB_SUMO_CONFIG}
  UB_SUMO_STEP_LENGTH=${UB_SUMO_STEP_LENGTH}
  UB_SUMO_GUI=${UB_SUMO_GUI}
  UB_SUMO_AUTO_START=${UB_SUMO_AUTO_START}
  UB_SUMO_TLS_MANAGER=${UB_SUMO_TLS_MANAGER}
  UB_SUMO_EMPTY_TRAFFIC=${UB_SUMO_EMPTY_TRAFFIC}
  AUTOWARE_MAP_PATH=${AUTOWARE_MAP_PATH}
  AUTOWARE_SERVICE=${AUTOWARE_SERVICE}
  AUTOWARE_CARLA_HOST=${AUTOWARE_CARLA_HOST}
  AUTOWARE_CARLA_PORT=${AUTOWARE_CARLA_PORT}
  AUTOWARE_VEHICLE_MODEL=${AUTOWARE_VEHICLE_MODEL}
  AUTOWARE_SENSOR_MODEL=${AUTOWARE_SENSOR_MODEL}
  AUTOWARE_E2E_SIMULATOR_TYPE=${AUTOWARE_E2E_SIMULATOR_TYPE}
  AUTOWARE_CARLA_POINTCLOUD_RELAY=${AUTOWARE_CARLA_POINTCLOUD_RELAY}
  UB_AUTOWARE_CARLA_IMU_RELAY=${UB_AUTOWARE_CARLA_IMU_RELAY}
  UB_AUTOWARE_CARLA_PLANNING_PRESET=${UB_AUTOWARE_CARLA_PLANNING_PRESET}
  UB_AUTOWARE_EGO_ONLY_PERCEPTION=${UB_AUTOWARE_EGO_ONLY_PERCEPTION}
  UB_AUTOWARE_CARLA_EGO_ROLE_NAME=${UB_AUTOWARE_CARLA_EGO_ROLE_NAME}
  UB_AUTOWARE_CARLA_VEHICLE_TYPE=${UB_AUTOWARE_CARLA_VEHICLE_TYPE}
  UB_AUTOWARE_CARLA_VEHICLE_COLOR=${UB_AUTOWARE_CARLA_VEHICLE_COLOR}
  UB_AUTOWARE_CARLA_SPAWN_POINT=${UB_AUTOWARE_CARLA_SPAWN_POINT}
  UB_AUTOWARE_CARLA_PROJECT_SPAWN_TO_ROAD=${UB_AUTOWARE_CARLA_PROJECT_SPAWN_TO_ROAD}
  UB_AUTOWARE_CARLA_OBJECTS_DEFINITION_FILE=${UB_AUTOWARE_CARLA_OBJECTS_DEFINITION_FILE:-<package default>}
  UB_AUTOWARE_CARLA_RAW_VEHICLE_CMD_CONVERTER_CONFIG=${UB_AUTOWARE_CARLA_RAW_VEHICLE_CMD_CONVERTER_CONFIG}
  UB_AUTOWARE_CARLA_ALIGN_BASE_LINK_TO_REAR_AXLE=${UB_AUTOWARE_CARLA_ALIGN_BASE_LINK_TO_REAR_AXLE}
  UB_AUTOWARE_CARLA_PUBLISH_SIMULATOR_TF=${UB_AUTOWARE_CARLA_PUBLISH_SIMULATOR_TF}
  UB_AUTOWARE_LIDAR_DETECTION_MODEL=${UB_AUTOWARE_LIDAR_DETECTION_MODEL}
  UB_AUTOWARE_CARLA_FILTER_EGO_LIDAR_POINTS=${UB_AUTOWARE_CARLA_FILTER_EGO_LIDAR_POINTS}
  UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_X_MIN=${UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_X_MIN}
  UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_X_MAX=${UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_X_MAX}
  UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_Y_MIN=${UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_Y_MIN}
  UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_Y_MAX=${UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_Y_MAX}
  UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_Z_MIN=${UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_Z_MIN}
  UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_Z_MAX=${UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_Z_MAX}
  UB_AUTOWARE_CARLA_EXTERNAL_TICK_TIMEOUT=${UB_AUTOWARE_CARLA_EXTERNAL_TICK_TIMEOUT}
  UB_AUTOWARE_CARLA_DISABLE_STEER_CONVERGENCE_HOLD=${UB_AUTOWARE_CARLA_DISABLE_STEER_CONVERGENCE_HOLD}
  UB_AUTOWARE_OPERATION_MODE_SHIM=${UB_AUTOWARE_OPERATION_MODE_SHIM}
  UB_AUTOWARE_CARLA_TUNE_SPEED=${UB_AUTOWARE_CARLA_TUNE_SPEED}
  UB_AUTOWARE_CARLA_MAX_VEL=${UB_AUTOWARE_CARLA_MAX_VEL}
  UB_AUTOWARE_CARLA_MAX_ACCEL=${UB_AUTOWARE_CARLA_MAX_ACCEL}
  UB_AUTOWARE_CARLA_ENGAGE_VELOCITY=${UB_AUTOWARE_CARLA_ENGAGE_VELOCITY}
  UB_AUTOWARE_CARLA_TURN_LATERAL_ACCEL_LIMITS=${UB_AUTOWARE_CARLA_TURN_LATERAL_ACCEL_LIMITS}
  UB_AUTOWARE_CARLA_MIN_TURN_VEL=${UB_AUTOWARE_CARLA_MIN_TURN_VEL}
  UB_AUTOWARE_CARLA_INTERSECTION_TURN_VEL=${UB_AUTOWARE_CARLA_INTERSECTION_TURN_VEL}
  UB_AUTOWARE_CARLA_THROTTLE_GAIN=${UB_AUTOWARE_CARLA_THROTTLE_GAIN}
  UB_AUTOWARE_CARLA_MAX_THROTTLE=${UB_AUTOWARE_CARLA_MAX_THROTTLE}
  UB_AUTOWARE_CARLA_MAX_BRAKE=${UB_AUTOWARE_CARLA_MAX_BRAKE}
  UB_AUTOWARE_CARLA_BRAKE_DEADBAND=${UB_AUTOWARE_CARLA_BRAKE_DEADBAND}
  UB_AUTOWARE_CARLA_THROTTLE_TAU=${UB_AUTOWARE_CARLA_THROTTLE_TAU}
  UB_AUTOWARE_CARLA_BRAKE_TAU=${UB_AUTOWARE_CARLA_BRAKE_TAU}
  UB_AUTOWARE_CARLA_SOFT_SPEED_LIMIT=${UB_AUTOWARE_CARLA_SOFT_SPEED_LIMIT}
  UB_AUTOWARE_CARLA_SPEED_TAPER_START=${UB_AUTOWARE_CARLA_SPEED_TAPER_START}
  UB_AUTOWARE_CARLA_LONGITUDINAL_CONTROL_MODE=${UB_AUTOWARE_CARLA_LONGITUDINAL_CONTROL_MODE}
  UB_AUTOWARE_CARLA_NATIVE_THROTTLE_KP=${UB_AUTOWARE_CARLA_NATIVE_THROTTLE_KP}
  UB_AUTOWARE_CARLA_NATIVE_ACCEL_GAIN=${UB_AUTOWARE_CARLA_NATIVE_ACCEL_GAIN}
  UB_AUTOWARE_CARLA_NATIVE_BRAKE_GAIN=${UB_AUTOWARE_CARLA_NATIVE_BRAKE_GAIN}
  UB_AUTOWARE_CARLA_NATIVE_BRAKE_ACCEL_DEADBAND=${UB_AUTOWARE_CARLA_NATIVE_BRAKE_ACCEL_DEADBAND}
  UB_AUTOWARE_CARLA_NATIVE_BRAKE_SPEED_ERROR_DEADBAND=${UB_AUTOWARE_CARLA_NATIVE_BRAKE_SPEED_ERROR_DEADBAND}
  UB_AUTOWARE_CARLA_STOP_STEER_RECENTER=${UB_AUTOWARE_CARLA_STOP_STEER_RECENTER}
  UB_AUTOWARE_CARLA_STOP_STEER_SPEED_THRESHOLD=${UB_AUTOWARE_CARLA_STOP_STEER_SPEED_THRESHOLD}
  UB_AUTOWARE_CARLA_STOP_STEER_DESIRED_SPEED_THRESHOLD=${UB_AUTOWARE_CARLA_STOP_STEER_DESIRED_SPEED_THRESHOLD}
  UB_AUTOWARE_CARLA_STOP_STEER_BRAKE_THRESHOLD=${UB_AUTOWARE_CARLA_STOP_STEER_BRAKE_THRESHOLD}
  UB_AUTOWARE_CARLA_PUBLISH_DETECTED_OBJECTS=${UB_AUTOWARE_CARLA_PUBLISH_DETECTED_OBJECTS}
  UB_AUTOWARE_CARLA_DETECTED_OBJECTS_TOPIC=${UB_AUTOWARE_CARLA_DETECTED_OBJECTS_TOPIC}
  UB_AUTOWARE_CARLA_DETECTED_OBJECTS_FRAME_ID=${UB_AUTOWARE_CARLA_DETECTED_OBJECTS_FRAME_ID}
  UB_AUTOWARE_CARLA_DETECTED_OBJECTS_MAX_DISTANCE=${UB_AUTOWARE_CARLA_DETECTED_OBJECTS_MAX_DISTANCE}
  UB_AUTOWARE_CARLA_DETECTED_OBJECTS_ROLE_NAME=${UB_AUTOWARE_CARLA_DETECTED_OBJECTS_ROLE_NAME}
  UB_AUTOWARE_CAMERA_FOLLOW=${UB_AUTOWARE_CAMERA_FOLLOW}
  UB_AUTOWARE_CAMERA_FOLLOW_ROLE_NAMES=${UB_AUTOWARE_CAMERA_FOLLOW_ROLE_NAMES}
  UB_AUTOWARE_CAMERA_FOLLOW_DISTANCE_M=${UB_AUTOWARE_CAMERA_FOLLOW_DISTANCE_M}
  UB_AUTOWARE_CAMERA_FOLLOW_HEIGHT_M=${UB_AUTOWARE_CAMERA_FOLLOW_HEIGHT_M}
  UB_AUTOWARE_CAMERA_FOLLOW_PITCH_DEG=${UB_AUTOWARE_CAMERA_FOLLOW_PITCH_DEG}
  UB_AUTOWARE_CAMERA_FOLLOW_UPDATE_HZ=${UB_AUTOWARE_CAMERA_FOLLOW_UPDATE_HZ}

Useful overrides:
  UB_SUMO_CONFIG=Town01.sumocfg $(basename "$0")
  UB_TRAFFIC_ORCHESTRATOR=none $(basename "$0")
  UB_SUMO_GUI=0 $(basename "$0")
  UB_SUMO_EMPTY_TRAFFIC=1 $(basename "$0")
  UB_SUMO_EXTRA_ARGS="--debug" $(basename "$0")
  UB_AUTOWARE_CARLA_PLANNING_PRESET=0 $(basename "$0")
  UB_AUTOWARE_EGO_ONLY_PERCEPTION=0 $(basename "$0")
  UB_AUTOWARE_CARLA_IMU_RELAY=0 $(basename "$0")
  UB_AUTOWARE_CARLA_SPAWN_POINT="-214.130,3.295,0.030,0,0,0.722" $(basename "$0")
  UB_AUTOWARE_CARLA_VEHICLE_TYPE=vehicle.lincoln.mkz_2017 $(basename "$0")
  UB_AUTOWARE_CARLA_VEHICLE_COLOR=255,255,255 $(basename "$0")
  UB_AUTOWARE_CARLA_PROJECT_SPAWN_TO_ROAD=False $(basename "$0")
  UB_AUTOWARE_CARLA_OBJECTS_DEFINITION_FILE=/host_data/custom_objects.json $(basename "$0")
  UB_AUTOWARE_CARLA_RAW_VEHICLE_CMD_CONVERTER_CONFIG=/host_data/custom_converter.yaml $(basename "$0")
  UB_AUTOWARE_CARLA_ALIGN_BASE_LINK_TO_REAR_AXLE=0 $(basename "$0")
  UB_AUTOWARE_CARLA_PUBLISH_SIMULATOR_TF=0 $(basename "$0")
  UB_AUTOWARE_CARLA_PUBLISH_DETECTED_OBJECTS=0 $(basename "$0")
  UB_AUTOWARE_CARLA_DETECTED_OBJECTS_TOPIC=/perception/object_recognition/detection/objects $(basename "$0")
  UB_AUTOWARE_LIDAR_DETECTION_MODEL=centerpoint/centerpoint_tiny $(basename "$0")
  UB_AUTOWARE_CARLA_FILTER_EGO_LIDAR_POINTS=0 $(basename "$0")
  UB_AUTOWARE_CARLA_EGO_LIDAR_FILTER_X_MAX=4.50 $(basename "$0")
  UB_AUTOWARE_CARLA_DISABLE_STEER_CONVERGENCE_HOLD=0 $(basename "$0")
  UB_AUTOWARE_OPERATION_MODE_SHIM=0 $(basename "$0")
  UB_AUTOWARE_CARLA_TUNE_SPEED=0 $(basename "$0")
  UB_AUTOWARE_CARLA_MAX_VEL=6.0 UB_AUTOWARE_CARLA_THROTTLE_GAIN=1.8 $(basename "$0")
  UB_AUTOWARE_CARLA_MIN_TURN_VEL=4.0 UB_AUTOWARE_CARLA_TURN_LATERAL_ACCEL_LIMITS=2.5,2.8,3.0 $(basename "$0")
  UB_AUTOWARE_CARLA_THROTTLE_GAIN=3.0 UB_AUTOWARE_CARLA_MAX_THROTTLE=0.65 $(basename "$0")
  UB_AUTOWARE_CARLA_BRAKE_DEADBAND=0.0 $(basename "$0")
  UB_AUTOWARE_CARLA_LONGITUDINAL_CONTROL_MODE=actuation $(basename "$0")
  UB_AUTOWARE_CARLA_NATIVE_BRAKE_ACCEL_DEADBAND=0.8 $(basename "$0")
  UB_AUTOWARE_CARLA_STOP_STEER_RECENTER=0 $(basename "$0")
  UB_AUTOWARE_CARLA_STOP_STEER_SPEED_THRESHOLD=0.10 $(basename "$0")
  AUTOWARE_RVIZ=false $(basename "$0")
  UB_KEEP_CARLA=1 UB_KEEP_SUMO=1 $(basename "$0")
  UB_AUTOWARE_CAMERA_FOLLOW=0 $(basename "$0")
  UB_AUTOWARE_CAMERA_FOLLOW_DISTANCE_M=10.0 UB_AUTOWARE_CAMERA_FOLLOW_HEIGHT_M=4.0 $(basename "$0")

Driving workflow:
  In RViz, localize, set a goal pose, wait for the route/trajectory, then click AUTO.
  The operation-mode shim makes AUTO available in this CARLA+SUMO simulator path.
  The IMU relay feeds UB Lincoln's /sensing/imu/imu_data pipeline so AEB does not
  emergency-stop while waiting for IMU data.

Options:
  --dry-run  Validate prerequisites and print commands without starting containers.
  --help     Show this help text.
EOF
}

setup_hint() {
  cat <<EOF

Setup hints:
  CARLA build:
    bash scripts/install_ub_carla.sh ${BUILD_FOLDER}

  Autoware submodule, image, and UB HD map:
    cd Autoware
    ./setup_autoware.sh

  Autoware DDS host settings:
    cd ${AUTOWARE_DOCKER_DIR}
    ../scripts/host_config_dds.bash
EOF
}

collect_preflight_failures() {
  local failures_ref="$1"
  local -n preflight_failures="${failures_ref}"

  collect_docker_preflight_failures preflight_failures

  if [[ ! -x "${CARLA_DIR}/Builds/${BUILD_FOLDER}/CarlaUE4.sh" ]]; then
    preflight_failures+=("Missing executable CARLA build: ${CARLA_DIR}/Builds/${BUILD_FOLDER}/CarlaUE4.sh")
  fi

  if ! find "${CARLA_DIR}/Builds/${BUILD_FOLDER}/PythonAPI/carla/dist" -maxdepth 1 -type f -name 'carla-*-cp310-*.whl' -print -quit 2>/dev/null | grep -q .; then
    preflight_failures+=("Missing CARLA Python cp310 wheel under ${CARLA_DIR}/Builds/${BUILD_FOLDER}/PythonAPI/carla/dist.")
  fi

  collect_sumo_preflight_failures preflight_failures

  if [[ ! -d "${BRIDGE_DIR}/autoware_carla_interface" ]]; then
    preflight_failures+=("Missing custom autoware_carla_interface package: ${BRIDGE_DIR}/autoware_carla_interface")
  fi

  if [[ ! -d "${AUTOWARE_DOCKER_DIR}" ]]; then
    preflight_failures+=("Missing Autoware Docker directory: ${AUTOWARE_DOCKER_DIR}")
  elif [[ ! -f "${AUTOWARE_DOCKER_DIR}/compose.yml" && ! -f "${AUTOWARE_DOCKER_DIR}/docker-compose.yml" && ! -f "${AUTOWARE_DOCKER_DIR}/docker-compose.yaml" ]]; then
    preflight_failures+=("Autoware Docker directory does not contain a Compose file: ${AUTOWARE_DOCKER_DIR}")
  fi

  if ! has_files "${AUTOWARE_HOST_MAP_DIR}"; then
    preflight_failures+=("Missing or empty Autoware UB HD map directory: ${AUTOWARE_HOST_MAP_DIR}")
  fi

  if [[ -z "${DISPLAY:-}" ]]; then
    preflight_failures+=("DISPLAY is not set. Run from a graphical Linux session or configure X11 forwarding.")
  fi

  if [[ ! -d /tmp/.X11-unix ]]; then
    preflight_failures+=("Missing /tmp/.X11-unix. CARLA and SUMO GUI need the host X11 socket mounted into Docker.")
  fi
}

print_dry_run() {
  cat <<EOF
Dry run passed. The launcher would run:

  cd ${CARLA_DIR}
  BUILD_FOLDER=${BUILD_FOLDER} \\
  CARLA_MAP_PATH=${CARLA_MAP_PATH} \\
  CARLA_ARGS=${CARLA_ARGS} \\
  docker compose up --build -d carla map-loader

  cd ${CARLA_DIR}
EOF

  if [[ "${UB_TRAFFIC_ORCHESTRATOR}" == "sumo" ]]; then
    cat <<EOF

  cd ${CARLA_DIR}
  UB_SUMO_CONFIG=${UB_SUMO_CONFIG} \\
  UB_SUMO_STEP_LENGTH=${UB_SUMO_STEP_LENGTH} \\
  UB_SUMO_GUI=${UB_SUMO_GUI} \\
  UB_SUMO_AUTO_START=${UB_SUMO_AUTO_START} \\
  UB_SUMO_TLS_MANAGER=${UB_SUMO_TLS_MANAGER} \\
  UB_SUMO_EMPTY_TRAFFIC=${UB_SUMO_EMPTY_TRAFFIC} \\
  docker compose up --build -d sumo-bridge
EOF
  else
    cat <<EOF

  cd ${CARLA_DIR}
  UB_CARLA_STEP_LENGTH=${UB_SUMO_STEP_LENGTH} \\
  docker compose up --build -d time-master
EOF
  fi

  cat <<EOF

  cd ${AUTOWARE_DOCKER_DIR}
  docker compose up -d ${AUTOWARE_SERVICE}
  # autoware_carla_interface is mounted by the Autoware Compose service.
  docker compose exec ${AUTOWARE_SERVICE} bash -lc 'test -f /autoware/src/universe/autoware_universe/simulator/autoware_carla_interface/package.xml'
  docker compose exec ${AUTOWARE_SERVICE} bash -lc 'cd /autoware && colcon build --symlink-install --packages-select autoware_carla_interface'
EOF

  if [[ "${UB_AUTOWARE_CAMERA_FOLLOW}" == "1" ]]; then
    cat <<EOF

  cd ${CARLA_DIR}
  UB_AUTOWARE_CAMERA_FOLLOW_ROLE_NAMES=${UB_AUTOWARE_CAMERA_FOLLOW_ROLE_NAMES} \\
  UB_AUTOWARE_CAMERA_FOLLOW_DISTANCE_M=${UB_AUTOWARE_CAMERA_FOLLOW_DISTANCE_M} \\
  UB_AUTOWARE_CAMERA_FOLLOW_HEIGHT_M=${UB_AUTOWARE_CAMERA_FOLLOW_HEIGHT_M} \\
  UB_AUTOWARE_CAMERA_FOLLOW_PITCH_DEG=${UB_AUTOWARE_CAMERA_FOLLOW_PITCH_DEG} \\
  docker compose up --build -d camera-follow
EOF
  fi

  cat <<EOF

  # In the Autoware launch shell:
  #   UB_AUTOWARE_CARLA_TUNE_SPEED=${UB_AUTOWARE_CARLA_TUNE_SPEED} patches simulation speed limits.
  #   UB_AUTOWARE_CARLA_IMU_RELAY=${UB_AUTOWARE_CARLA_IMU_RELAY} relays CARLA IMU into UB Lincoln's NovAtel raw IMU input.
  #   UB_AUTOWARE_OPERATION_MODE_SHIM=${UB_AUTOWARE_OPERATION_MODE_SHIM} publishes simulator operation-mode availability.
  docker compose exec ${AUTOWARE_SERVICE} bash -lc 'ros2 launch autoware_carla_interface ... external_tick:=True vehicle_type:=${UB_AUTOWARE_CARLA_VEHICLE_TYPE} spawn_point:=${UB_AUTOWARE_CARLA_SPAWN_POINT} & ros2 run topic_tools relay ... & ros2 launch autoware_launch e2e_simulator.launch.xml simulator_type:=awsim ...'

After launch:
  Localize, set a goal pose, wait for route planning, then click AUTO.
EOF
}

cleanup() {
  local exit_code="$?"

  if [[ "${CAMERA_FOLLOW_STARTED}" -eq 1 ]]; then
    echo "Stopping CARLA spectator camera follow."
    stop_compose_service camera-follow
    CAMERA_FOLLOW_STARTED=0
  fi

  if [[ "${AUTOWARE_LAUNCH_STARTED}" -eq 1 && "${UB_KEEP_AUTOWARE_ROS}" != "1" ]]; then
    cleanup_autoware_launch_processes "Stopping Autoware ROS launch processes. Set UB_KEEP_AUTOWARE_ROS=1 to leave them running." AUTOWARE_SUMO_CLEANUP_PATTERNS || true
    AUTOWARE_LAUNCH_STARTED=0
  fi

  if [[ "${SUMO_STARTED}" -eq 1 && "${UB_KEEP_SUMO}" != "1" ]]; then
    echo "Stopping SUMO bridge. Set UB_KEEP_SUMO=1 to leave it running."
    stop_compose_service sumo-bridge
    SUMO_STARTED=0
  fi

  if [[ "${TIME_MASTER_STARTED}" -eq 1 && "${UB_KEEP_TIME_MASTER}" != "1" ]]; then
    echo "Stopping CARLA-only time master. Set UB_KEEP_TIME_MASTER=1 to leave it running."
    stop_compose_service time-master
    TIME_MASTER_STARTED=0
  fi

  if [[ "${CARLA_STARTED}" -eq 1 && "${UB_KEEP_CARLA}" != "1" ]]; then
    echo "Stopping CARLA Compose stack. Set UB_KEEP_CARLA=1 to leave it running."
    cd "${CARLA_DIR}"
    docker compose down >/dev/null 2>&1 || true
    CARLA_STARTED=0
  fi

  exit "${exit_code}"
}

parse_common_args "$@"

run_preflight

if [[ "${DRY_RUN}" -eq 1 ]]; then
  print_dry_run
  exit 0
fi

trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

configure_autoware_host_dds
start_carla
start_traffic_orchestrator
start_autoware_container AUTOWARE_SUMO_CLEANUP_PATTERNS
build_mounted_autoware_bridge
start_camera_follow
launch_autoware_sumo
